### ISSUE TITLE
Is it possible to share your preprocessed data and pretrained model of LDIF?

### ISSUE THREAD

**Issue by pidan1231239** [google/ldif#2]
Hi Kyle:

Thanks for your great work and code on Local Deep Implicit Functions for 3D Shape!

I am trying to reproducing your results. However, I noticed that pretrained model checkpoint is on your TODO list. And preprocessed data is not released too.

I'd like to ask if it is possible to share your preprocessed data? Also when is the time to release the pretrained model checkpoint?

Best wishes
Cheng

**Comment by kylegenova** [comment]
Hello Cheng,

Re: Preprocessed data. We can (now) share preprocessed data on a per-request basis with people who have signed the ShapeNet user agreement. The reason we don't distribute it publicly is that we are trying to respect the ShapeNet license.

Re: Pretrained models. I know having access to pretrained models is very important and it is currently the highest priority for the codebase. Currently I think it will be at least a few weeks before they are ready to push to the public repository. In the mean time, I could share a checkpointed model with you directly, though it does not fully reproduce the paper numbers (the original paper checkpoints were trained for ~3.5M steps with a datacenter pipeline and are incompatible with the open-source release, so I am retraining the models locally). In the long-term it would be good to add local multi-gpu support so that training time is less of an issue.

**Comment by pidan1231239** [comment]
Thanks for your patience! I'll try to contact you personally to get a pretrained model.

**Comment by YuDeng** [comment]
> Hello Cheng,
> 
> Re: Preprocessed data. We can (now) share preprocessed data on a per-request basis with people who have signed the ShapeNet user agreement. The reason we don't distribute it publicly is that we are trying to respect the ShapeNet license.
> 
> Re: Pretrained models. I know having access to pretrained models is very important and it is currently the highest priority for the codebase. Currently I think it will be at least a few weeks before they are ready to push to the public repository. In the mean time, I could share a checkpointed model with you directly, though it does not fully reproduce the paper numbers (the original paper checkpoints were trained for ~3.5M steps with a datacenter pipeline and are incompatible with the open-source release, so I am retraining the models locally). In the long-term it would be good to add local multi-gpu support so that training time is less of an issue.

Hi, really nice work! I wonder if I could get a pre-trained model as well. I'm working on 3D reconstruction tasks and want to compare with your work. Really appreciated!!

**Comment by yoyoshuang** [comment]
@chengzhag have you got the  pre-trained model , I also want to get the pre-trained model as well , would you please to share it with me, ThankYou!
